/** @type {import('tailwindcss').Config} */
module.exports = {
  mode: "jit",
  content: [
    "./assets/**/*.css",
    "./components/*.{vue,js}",
    "./components/**/*.{vue,js}",
    "./pages/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./*.{vue,js,ts}",
    "./nuxt.config.{js,ts}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#4D7ED1",
        secondary: "#4D4DD1",
        "navy-blue": "#152238",
        "off-white": "#F5F5F5",
        error: "#D14D4D",
      },
      fontFamily: {
        "nunito-black": ["nunito-black", "sans-serif"],
        "nunito-blackitalic": ["nunito-blackitalic", "sans-serif"],
        "nunito-bold": ["nunito-bold", "sans-serif"],
        "nunito-bolditalic": ["nunito-bolditalic", "sans-serif"],
        "nunito-extrabold": ["nunito-extrabold", "sans-serif"],
        "nunito-extrabolditalic": ["nunito-extrabolditalic", "sans-serif"],
        "nunito-extralight": ["nunito-extralight", "sans-serif"],
        "nunito-extralightitalic": ["nunito-extralightitalic", "sans-serif"],
        "nunito-italix": ["nunito-italic", "sans-serif"],
        "nunito-light": ["nunito-light", "sans-serif"],
        "nunito-lightitalic": ["nunito-lightitalic", "sans-serif"],
        "nunito-medium": ["nunito-medium", "sans-serif"],
        "nunito-mediumitalic": ["nunito-mediumitalic", "sans-serif"],
        "nunito-regular": ["nunito-regular", "sans-serif"],
        "nunito-semibold": ["nunito-semibold", "sans-serif"],
        "nunito-semibolditalic": ["nunito-semibolditalic", "sans-serif"],

        h1: ["nunito-bold", "sans-serif"],
        h2: ["nunito-bold", "sans-serif"],
        h3: ["nunito-regular", "sans-serif"],
        h4: ["nunito-bold", "sans-serif"],
        h5: ["nunito-bold", "sans-serif"],
        h6: ["nunito-bold", "sans-serif"],
        p: ["nunito-light", "sans-serif"],
      },
      fontSize: {
        "h1-mobile": "42px",
        "h2-mobile": "34px",
        "h3-mobile": "27px",
        "h4-mobile": "22px",
        "h5-mobile": "18px",
        "h6-mobile": "14px",
        "p-mobile": "14px",
        "h1-tablet": "48px",
        "h2-tablet": "39px",
        "h3-tablet": "31px",
        "h4-tablet": "25px",
        "h5-tablet": "20px",
        "h6-tablet": "16px",
        "p-tablet": "16px",
        "h1-laptop": "61px",
        "h2-laptop": "48px",
        "h3-laptop": "39px",
        "h4-laptop": "31px",
        "h5-laptop": "25px",
        "h6-laptop": "20px",
        "p-laptop": "20px",
      },
      screens: {
        sm: "640px",
        md: "768px",
        lg: "1050px",
        xl: "1280px",
        "2xl": "1536px",
      },
      maxWidth: {
        "content-large": "1100px",
        "content-medium": "688px",
        "content-medium/small": "600px",
        "content-small/medium": "352px",
        "content-small": "300px",
        "content-extra-small": "120px",
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
